# Generated by Django 2.0.5 on 2019-04-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
    ]
