# Generated by Django 2.0.1 on 2019-04-10 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='景点id')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='景点名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='景点描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ScenicSpot/%Y/%m', verbose_name='景点图片')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('type', models.CharField(default='景点', max_length=100, verbose_name='类型')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
    ]
