# Generated by Django 2.0.5 on 2019-04-17 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScenicSpot', '0002_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': '上传评论文件', 'verbose_name_plural': '上传评论文件'},
        ),
        migrations.AddField(
            model_name='upload',
            name='add_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间'),
        ),
    ]
