# Generated by Django 2.0.5 on 2019-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScenicSpot', '0003_auto_20190417_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name': '评论文件', 'verbose_name_plural': '评论文件'},
        ),
        migrations.AddField(
            model_name='scenicspot',
            name='times',
            field=models.IntegerField(default='0', verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploadexcel/%Y/%m', verbose_name='文件上传'),
        ),
    ]
