# Generated by Django 2.0.1 on 2019-04-09 19:35

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ScenicSpot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicSpotComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('scenicspot', models.CharField(max_length=50, verbose_name='景点名称')),
                ('comments', models.CharField(max_length=2000, verbose_name='评论')),
                ('Emotional_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='情感得分')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '景点评论',
                'verbose_name_plural': '景点评论',
            },
        ),
        migrations.CreateModel(
            name='UserBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('desc', models.CharField(blank=True, max_length=500, null=True, verbose_name='简介')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
                ('rich_content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='富文本内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UserBlog/%Y/%m', verbose_name='图片')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户博客',
                'verbose_name_plural': '用户博客',
            },
        ),
        migrations.CreateModel(
            name='UserFavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='收藏博客id')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='添加时间')),
                ('fav_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScenicSpot.ScenicSpot', verbose_name='景点')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
    ]
