# Generated by Django 2.0.5 on 2019-04-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenicspotcomments',
            name='spot_from',
            field=models.CharField(default='飞猪', max_length=50, verbose_name='来源'),
        ),
    ]
